@startuml
set namespaceSeparator .


class dfsm.dFSM  {
}


class dfsm.State <<abstract>> {
}


class dfsm.IntermediateState <<abstract>> {
}


class dfsm.StartState  {
  name : ID
}


class dfsm.FinishState  {
  name : ID
}


class dfsm.ActiveFormState  {
  name : ID
}


class dfsm.Event <<abstract>> {
}


class dfsm.IntentEvent  {
  intent : STRING
  name : ID
}


class dfsm.ActiveFormParameter  {
  name : ID
  type : ParameterType
}


class dfsm.ParameterSource <<abstract>> {
}


class dfsm.HRIParamResource  {
  ask_slot : STRING
}


class dfsm.Action <<abstract>> {
}


class dfsm.SpeakAction  {
  text : STRING
}


class dfsm.FireEventAction  {
  msg : STRING
}


class dfsm.Transition <<abstract>> {
}


class dfsm.SimpleTransition  {
}


class dfsm.OnEventTransition  {
}


dfsm.dFSM *--> dfsm.Event: events 1..*
dfsm.dFSM *--> dfsm.StartState: startState
dfsm.dFSM *--> dfsm.FinishState: finishState
dfsm.dFSM *--> dfsm.IntermediateState: states 1..*
dfsm.dFSM *--> dfsm.Transition: transitions 1..*
dfsm.State <|-- dfsm.StartState
dfsm.State <|-- dfsm.FinishState
dfsm.State <|-- dfsm.ActiveFormState
dfsm.IntermediateState <|-- dfsm.ActiveFormState
dfsm.StartState *--> dfsm.Action: actions 1..*
dfsm.FinishState *--> dfsm.Action: actions 1..*
dfsm.ActiveFormState *--> dfsm.ActiveFormParameter: params 1..*
dfsm.Event <|-- dfsm.IntentEvent
dfsm.ActiveFormParameter *--> dfsm.ParameterSource: source
dfsm.ParameterSource <|-- dfsm.HRIParamResource
dfsm.Action <|-- dfsm.SpeakAction
dfsm.Action <|-- dfsm.FireEventAction
dfsm.Transition <|-- dfsm.OnEventTransition
dfsm.Transition <|-- dfsm.SimpleTransition
dfsm.SimpleTransition o--> dfsm.State: from_state
dfsm.SimpleTransition o--> dfsm.State: to_state
dfsm.OnEventTransition o--> dfsm.State: from_state
dfsm.OnEventTransition o--> dfsm.State: to_state
dfsm.OnEventTransition o--> dfsm.Event: on_event

legend
  Match rules:
  |= Name  |= Rule details |
  | ParameterType | int\|float\|str\|bool |
  | ParameterDefault | STRING\|INT\|FLOAT\|BOOL |
  | FQN | ID (. ID)* |
  | SMID | Not(Keyword) ID |
  | Comment | \\/\\/.*$ |
  | Keyword | end\|state\|actions |
end legend

@enduml
